//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceSystemProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvoiceSystemDBEntities : DbContext
    {
        public InvoiceSystemDBEntities()
            : base("name=InvoiceSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tblinvoice_details> tblinvoice_details { get; set; }
        public virtual DbSet<tblinvoice_payments> tblinvoice_payments { get; set; }
        public virtual DbSet<tblinvoice_products> tblinvoice_products { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
        public virtual DbSet<tblweight> tblweights { get; set; }
    }
}
