//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoice_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblinvoice_details()
        {
            this.tblinvoice_products = new HashSet<tblinvoice_products>();
            this.tblinvoice_payments = new HashSet<tblinvoice_payments>();
        }
    
        public int invoice_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<double> total_amount { get; set; }
    
        public virtual tblcustomer tblcustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice_products> tblinvoice_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice_payments> tblinvoice_payments { get; set; }
    }
}
