//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceSystemProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblproduct()
        {
            this.tblinvoice_products = new HashSet<tblinvoice_products>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string weight { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> gst { get; set; }
        public Nullable<int> stock_quantity { get; set; }
        public string received_on { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice_products> tblinvoice_products { get; set; }
    }
}
